apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: task5
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "0.5"
      requests:
        cpu: "0.1"
    args:
      - -cpus
      - "1"
