apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: task5
spec:
  containers:
  - name: cpu-demo-ctr-2
    image: vish/stress
    args:
      - -cpus
      - "1"
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"
