apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: task5
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    args:
      - -cpus
      - "1"
    resources:
      limits:
        cpu: 500mi
      requests:
        cpu: 100mi
